# Rutas de archivos
data.path=data/
data.persons.name=persons.csv
data.products.name=products.csv
data.accounting.name=accounting.csv
data.logs.path=data/logs/uptc.log

# Validaciones de Persona
person.name.min=2
person.name.max=30
person.lastname.min=2
person.lastname.max=30

# Validaciones de Producto
product.description.min=3
product.description.max=50
product.price.max=999999.99
# Formato descripcion: UPPER (todo mayusculas) | TITLE (primera letra de cada palabra)
product.description.format=UPPER

# Validaciones de Contabilidad
accounting.description.min=3
accounting.description.max=100

# Paginado (registros por pagina)
ui.page.size=10

# Idioma (es | en | pt) ? por defecto espanol
app.language=en